const questions=[
    {   Id:1,
        Question:"what does CSS stands for???",
        A:"Count Strike Source",
        B:" Coorrective Style Sheet",
        C:"Cascading Style Sheet",
        D:"Computer Style Sheet",
        Ans:"B",
    
    },
    {   Id:2,
        Question:"what does php stands for???",
        A:"pheripheral printer",
        B:" print hypertext",
        C:"hypertext preprocessor",
        D:"perpheral preprocessor",
        Ans:"A",
    },
    {   Id:3,
        Question:"what does html stands for???",
        A:"hyper translator",
        B:" Hyper text markup language",
        C:"hypertext machine language",
        D:"hyper translator ,machine language",
        Ans:"C",
    },
    ]